// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYVWJVTdbskt5FxGA6h_t0sMGgOQZNUk',
    appId: '1:445964855256:web:4e8544be896ca905d3f4ad',
    messagingSenderId: '445964855256',
    projectId: 'app-streamin-flutter',
    authDomain: 'app-streamin-flutter.firebaseapp.com',
    databaseURL: 'https://app-streamin-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'app-streamin-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYK4R9LTirRLFoxoJsLurgxiW8L0oGJQ',
    appId: '1:445964855256:android:4187c46a2e87922bd3f4ad',
    messagingSenderId: '445964855256',
    projectId: 'app-streamin-flutter',
    databaseURL: 'https://app-streamin-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'app-streamin-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4CFd9YSuNzMfVxma9cK08DTmi1NkBpNM',
    appId: '1:445964855256:ios:a29446db4f8fa38cd3f4ad',
    messagingSenderId: '445964855256',
    projectId: 'app-streamin-flutter',
    databaseURL: 'https://app-streamin-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'app-streamin-flutter.appspot.com',
    iosBundleId: 'com.example.appStreProFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4CFd9YSuNzMfVxma9cK08DTmi1NkBpNM',
    appId: '1:445964855256:ios:a29446db4f8fa38cd3f4ad',
    messagingSenderId: '445964855256',
    projectId: 'app-streamin-flutter',
    databaseURL: 'https://app-streamin-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'app-streamin-flutter.appspot.com',
    iosBundleId: 'com.example.appStreProFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwYVWJVTdbskt5FxGA6h_t0sMGgOQZNUk',
    appId: '1:445964855256:web:7d3ca883658e6282d3f4ad',
    messagingSenderId: '445964855256',
    projectId: 'app-streamin-flutter',
    authDomain: 'app-streamin-flutter.firebaseapp.com',
    databaseURL: 'https://app-streamin-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'app-streamin-flutter.appspot.com',
  );

}